autenticacao/urls.py
from django.urls import path

from . import views

app_name = "autenticacao"

urlpatterns = [
    path("", views.login, name="login"),
    path("get_perfis/", views.get_perfis, name="get_perfis"),
    path("logout/", views.logout, name="logout"),
    path("recuperar-senha/", views.recuperar_senha, name="recuperar_senha"),
]

cadastros/urls.py
from django.urls import path

from . import views

app_name = "cadastros"

urlpatterns = [
    # CADASTRO DE DEPARTAMENTO
    path("departamentos/", views.departamentos, name="departamentos"),
    # path(
    #     "obter-departamento-por-id/",
    #     views.obter_departamento_por_id,
    #     name="obter-departamento-por-id",
    # ),
    # path(
    #     "excluir-departamento/", views.excluir_departamento, name="excluir-departamento"
    # ),
    # path(
    #     "pesquisar-departamento-por-nome",
    #     views.pesquisar_departamento_por_nome,
    #     name="pesquisar-departamento-por-nome",
    # ),
    # FIM DE CADASTRO DE DEPARTAMENTOS
]

config/urls.py
from django.urls import include, path

urlpatterns = [
    path("", include("autenticacao.urls")),
    path("core/", include("core.urls")),
    path("cadastros/", include("cadastros.urls")),
]

core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [path("main", views.main, name="main")]

cadastros/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models.deletion import ProtectedError


class Departamento(models.Model):
    nome = models.CharField(max_length=500)
    sigla = models.CharField(max_length=30)

    def delete(self, *args, **kwargs):
        if self.usuario_set.exists():
            raise ProtectedError(
                "Não é possível excluir este departamento, pois ele possui usuarios vinculados.",
                self,
            )
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.nome


class Perfil(models.Model):
    nome = models.CharField(max_length=100, unique=True)

    def delete(self, *args, **kwargs):
        if self.usuario_set.exists():
            raise ProtectedError(
                "Não é possível excluir este perfil, pois ele possui usuarios vinculados.",
                self,
            )
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.nome


class UsuarioManager(BaseUserManager):
    def create_user(self, email, nome, password=None):
        if not email:
            raise ValueError("O usuário deve ter um endereço de e-mail")
        user = self.model(email=self.normalize_email(email), nome=nome)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, nome, password=None):
        user = self.create_user(email, nome, password)
        user.is_admin = True
        user.save(using=self._db)
        return user


class Usuario(AbstractBaseUser):
    nome = models.CharField(max_length=300)
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    departamento = models.ForeignKey(Departamento, on_delete=models.PROTECT)
    perfis = models.ManyToManyField(Perfil)

    objects = UsuarioManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["nome"]

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    def tem_perfil(self, perfil_nome):
        return self.perfis.filter(nome=perfil_nome).exists()

sistema/models.py
from django.db import models

# Create your models here.

autenticacao/views.py
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.core.mail import send_mail
from django.http import JsonResponse
from django.shortcuts import redirect, render

from cadastros.models import Usuario


def login(request):
    if request.method == "POST":
        email = request.POST.get("txtEmail")
        senha = request.POST.get("txtSenha")
        perfil_id = request.POST.get("slcPerfil")

        usuario = authenticate(request, username=email, password=senha)

        if usuario is not None and perfil_id:
            perfis_usuario = usuario.perfis.filter(id=perfil_id)
            if perfis_usuario.exists():
                request.session.flush()
                auth_login(request, usuario)

                request.session["id_atual"] = usuario.id
                request.session["email_atual"] = usuario.email
                request.session["departamento_id_atual"] = usuario.departamento.id
                request.session["departametno_nome_atual"] = usuario.departamento.nome
                request.session["departametno_sigla_atual"] = usuario.departamento.sigla
                request.session["perfil_atual"] = perfis_usuario.first().nome
                request.session["perfis"] = list(
                    usuario.perfis.values_list("nome", flat=True)
                )

                request.session.set_expiry(14400)

                messages.success(request, "Login realizado com sucesso!")

                if request.session.get("perfil_atual") in {
                    "Administrador",
                    "Estoquista",
                    "Vendedor",
                }:
                    return redirect("core:main")
            else:
                messages.error(request, "Perfil inválido!")
        else:
            if usuario is None:
                messages.error(request, "Senha errada!")
            else:
                messages.error(request, "Usuários ou senha inválido!")

    return render(request, "login.html")


def get_perfis(request):
    email = request.GET.get("email", "")
    perfil = []

    if Usuario.objects.filter(email=email).exists():
        usuario = Usuario.objects.get(email=email)
        perfis = usuario.perfis.all().values("id", "nome")
        data = {"perfis": list(perfis), "usuario_existe": True}
    else:
        data = {"usuario_existe": False}
    return JsonResponse(data)


def logout(request):
    request.session.flush()
    auth_logout(request)
    messages.success(request, "Logout realizado com sucesso!")

    return redirect("autenticacao:login")


def recuperar_senha(request):
    if request.method == "POST":
        email = request.POST.get("email")
        try:
            usuario = Usuario.objects.get(email=email)
            send_mail(
                "Recuperação de senha",
                f"Sua senha é: {usuario.password}",
                "seu_email@dominio.com",
                [email],
                fail_silently=False,
            )
            return JsonResponse(
                {"success": True, "message": "Senha enviada para o email informado."}
            )
        except Usuario.DoesNotExist:
            return JsonResponse({"success": False, "message": "Email não encontrado."})
    return JsonResponse({"success": False, "message": "Método inválido."})

cadastros/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Count, ExpressionWrapper, F, OuterRef, Q, Subquery, Sum
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from .models import Departamento, Perfil, Usuario


# CADASTRO DE DEPARTAMENTOS
@login_required
def departamentos(request):
    if request.session.get("perfil_atual") not in {"Administrador"}:
        messages.error(request, "Você não é administrador!")
        return redirect("core:main")
    if request.method == "post":
        messages.success(request, "Implementar depois.")
    departamento_lista = (
        Departamento.objects.all().exclude(nome__iexact="Geral").order_by("nome")
    )
    paginator = Paginator(departamento_lista, settings.NUMBER_GRID_PAGES)
    numero_pagina = request.GET.get("page")
    page_obj = paginator.get_page(numero_pagina)
    return render(request, "departamentos.html", {"page_obj": page_obj})

core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required
def main(request):
    return render(request, "main.html")

sistema/views.py
from django.shortcuts import render

# Create your views here.

autenticacao/templates/login.html
{% extends 'index.html' %}
{% block conteudo %}
    <div class="container">
        <h2>Login</h2>
        <form method="POST" action="{% url 'autenticacao:login' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="txtEmail">E-mail</label>
                <input type="email"
                       class="form-control"
                       id="txtEmail"
                       name="txtEmail"
                       required
                       autocomplete="off">
                <div id="divEmailError" class="error-message"></div>
            </div>
            <div class="form-group hidden-group" id="divSenha">
                <label for="txtSenha">Senha</label>
                <input type="password"
                       class="form-control"
                       id="txtSenha"
                       name="txtSenha"
                       required
                       autocomplete="new-password">
            </div>
            <div class="form-group hidden-group" id="divPerfil">
                <label for="perfil">Perfil</label>
                <select class="form-control" id="slcPerfil" name="slcPerfil" required></select>
            </div>
            <div id="divSpace" class="space"></div>
            <button type="submit" class="btn btn-light">Entrar</button>
            <a href="#" id="btnEsqueciSenha" class="btn btn-light">Esqueci minha senha</a>
        </form>
    </div>
    <script>
    $(document).ready(function() {
        $('#txtEmail').on('input', function() {
            var email = $(this).val();
            $('#divPerfil').addClass('hidden-group');
            $('#divSenha').addClass('hidden-group');
            $('#slcPerfil').empty();
            $('#divEmailError').text(' ').removeClass('visible');

            if (email.length > 0) {
                $.ajax({
                    url: "{% url 'autenticacao:get_perfis' %}",
                    data: {'email': email},
                    success: function(data) {
                        if (data.usuario_existe) {
                            if (data.perfis.length > 0) {
                                $('#slcPerfil').empty();
                                data.perfis.forEach(function(perfil) {
                                    $('#slcPerfil').append(new Option(perfil.nome, perfil.id));
                                });
                                $('#divPerfil').removeClass('hidden-group');
                                $('#divSenha').removeClass('hidden-group');
                            } else {
                                toastr.error("Nenhum perfil encontrado para este e-mail.", "Erro");
                            }
                        } else {
                            $('#divEmailError').text('.').addClass('visible');
                        }
                    }
                });
            }
        });

        $('#btnEsqueciSenha').click(function(event) {
            event.preventDefault();
            const email = $('#txtEmail').val();
            if (!email) {
                toastr.error('Por favor, insira seu email.');
                return;
            }
            $.ajax({
                type: 'POST',
                url: "{% url 'autenticacao:recuperar_senha' %}",
                data: {
                    email: email,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function(response) {
                    if (response.success) {
                        toastr.success(response.message);
                    } else {
                        toastr.error(response.message);
                    }
                },
                error: function() {
                    toastr.error('Ocorreu um erro ao tentar recuperar a senha.');
                }
            });
        });
    });
    </script>
{% endblock conteudo %}

cadastros/templates/departamentos.html
{% extends 'master.html' %}
{% load static %}
{% block conteudo %}
    <br>
    <div class="container">
        <div class="form-group row align-items-center mb-4">
            <div class="col-12 text-center">
                <h1 class="display-5 font-weight-bold text-primary">Cadastro de Departamentos</h1>
                <hr class="mt- mb-3 border-primary">
            </div>
        </div>
        <fieldset class="fieldset-custom">
            <legend>
                {% if page_obj.paginator.count == 0 %}
                    Nenhum registro encontrado
                {% elif page_obj.paginator.count == 1 %}
                    1 registro encontrado
                {% else %}
                    {{ page_obj.paginator.count }} registros encontrados
                {% endif %}
            </legend>
            <div class="form-group row align-items-center">
                <div class="col-auto">
                    <img src="{% static 'img/search.png' %}"
                         width="20px"
                         height="20px"
                         alt="Pesquisar">
                </div>
                <div class="text-left">
                    <label for="txtBuscaNome" class="col-form-label">Pesquisar por nome:</label>
                </div>
                <div class="col">
                    <input type="text"
                           class="form-control"
                           id="txtBuscaNome"
                           placeholder="Digite o nome do departamento"
                           value="{{ query }}">
                </div>
            </div>
            <div class="departamentos-table">{% include 'departamentos_table.html' %}</div>
        </fieldset>
        <hr>
        To be continued...
    </div>
{% endblock conteudo %}

cadastros/templates/departamentos_table.html
{% load static %}
<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th scope-"col">#</th>
            <th scope-"col">NOME</th>
            <th scope-"col">SIGLA</th>
            <th scope-"col">AÇÕES</th>
        </tr>
    </thead>
    <tbody>
        {% for departamento in page_obj %}
            <tr class="departamento-row" data-id={{ departamento.id }}>
                <td>{{ forloop.counter }}</td>
                <td>{{ departamento.nome }}</td>
                <td>{{ departamento.sigla }}</td>
                <td>
                    <button class="btn btn-sm delete-btn" data-id="{{ departamento.id }}">
                        <img src="{% static 'img/delete.png' %}"
                             width="20px"
                             height="20px"
                             alt="Excluir">
                    </button>
                    <button class="btn btn-sm">
                        <img src="{% static 'img/update.png' %}"
                             width="20px"
                             height="20px"
                             alt="Alterar">
                    </button>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1&query={{ query }}">&laquo; primeira</a>
            </li>
            <li class="page-item">
                <a class="page-link"
                   href="?page={{ page_obj.previous_page_number }}&query={{ query }}">&lsaquo; anterior</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">&laquo; primeira</span>
            </li>
            <li class="page-item disabled">
                <span class="page-link">&lsaquo; anterior</span>
            </li>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item active">
                    <span class="page-link">{{ num }}</span>
                </li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}&query={{ query }}">{{ num }}</a>
                </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link"
                   href="?page={{ page_obj.next_page_number }}&query={{ query }}">próxima &rsaquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link"
                   href="?page={{ page_obj.paginator.num_pages }}&query={{ query }}">última &raquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">próxima &rsaquo;</span>
            </li>
            <li class="page-item disabled">
                <span class="page-link">última &raquo;</span>
            </li>
        {% endif %}
    </ul>
</nav>

core/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>:: PYPEL ::</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/toastr.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/index.css' %}">
        <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">
        <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/toastr.min.js' %}"></script>
    </head>
    <body>
        <div class="container-fluid vh-100 d-flex flex-column">
            <div class="row flex-grow-1">
                <div class="col col-blue d-flex flex-column justify-content-center"
                     style="background-color: #efc9c9">
                    <!-- Conteúdo carregado dinamicamente -->
                    <div class="content">
                        {% block conteudo %}
                        {% endblock conteudo %}
                    </div>
                </div>
                <div class="col col-white d-flex flex-column justify-content-center align-items-center">
                    <div class="text-center">
                        <img src="{% static 'img/logo.png' %}"
                             alt="Logomarca do Sistema de Gerenciamento de Papelaria"
                             width="300px">
                        <div class="footer-text text-center py-3">
                            Este sistema está licenciado sob
                            <a href="https://creativecommons.org/licenses/by/4.0/"
                               target="_blank"
                               rel="noopener noreferrer"
                               style="color: #0000FF">Licença Creative Commons&copy; 4.0</a>
                            <img src="{% static 'img/creativecommons.png' %}"
                                 width="45px"
                                 alt="Creative Commons">
                            <br>
                            Disponível para download em
                            <a href="https://github.com/ciniro/pypel"
                               target="_blank"
                               rel="noopener noreferrer"
                               style="color: #0000FF">github.com/ciniro/pypel</a>
                            <img src="{% static 'img/github.png' %}" width="15px" alt="GitHub">
                            <button id="btnSobre" class="btn btn-outline-secondary p-0">Sobre</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- sobre -->
        <div class="modal fade"
             id="jnlSobre"
             tabindex="-1"
             role="dialog"
             aria-labelledby="jnlSobreRotulo"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="jnlSobreRotulo">Sobre o PYPEL</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body text-justify">
                        <p>
                            O PYPEL é um sistema de gerenciamento de papelaria que permite a gestão do estoque de produtos
                            fornecendo um sistema de entrada e uma tela de venda que permite dar saída nos itens cadastrados no estoque.
                        </p>
                        <p>
                            O sistema é utilizado pelo Prof. Dr. Ciniro Nametala (<a href="http://lattes.cnpq.br/3258604768114823">lattes</a>)
                            com o apoio das turmas da disciplina de Programação WEB do curso de Bacharelado em Engenharia de Computação do Instituto Federal de Minas Gerais - <i>Campus</i> Bambuí, e está licenciado sob
                            <a href="https://creativecommons.org/licenses/by/4.0/"
                               target="_blank"
                               rel="noopener noreferrer">Licença Creative Commons&copy; 4.0</a>
                            <img src="{% static 'img/creativecommons.png' %}"
                                 width="45px"
                                 alt="Creative Commons">
                            .
                        </p>
                        <p>
                            O PYPEL foi desenvolvido em <a href="https://www.python.org/"
    target="_blank"
    rel="noopener noreferrer">Python</a>
                            <img src="{% static 'img/python.png' %}" width="15px" alt="Python">
                            ,
                            <a href="https://www.djangoproject.com/"
                               target="_blank"
                               rel="noopener noreferrer">Django</a>
                            <img src="{% static 'img/django.png' %}" width="15px" alt="Django">
                            e
                            <a href="https://www.postgresql.org/"
                               target="_blank"
                               rel="noopener noreferrer">PostgreSQL</a>
                            <img src="{% static 'img/postgresql.png' %}" width="15px" alt="PostgreSQL">
                            .
                            O código fonte, juntamente com as instruções de instalação, estão disponíveis para <i>download</i> em
                            <a href="https://github.com/ciniro/pypel"
                               target="_blank"
                               rel="noopener noreferrer">github.com/ciniro/pypel</a>
                            <img src="{% static 'img/github.png' %}" width="15px" alt="GitHub">
                            . Você pode contribuir com o projeto, reportando erros, sugerindo melhorias ou mesmo implementando novas funcionalidades você mesmo. Por favor, use o GitHub para isso.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <script>
        $(document).ready(function () {
            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": true,
                "progressBar": true,
                "positionClass": "toast-top-right",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "3000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            };

            {% if messages %}
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        toastr.error("{{ message }}", "Erro");
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                        toastr.success("{{ message }}", "Sucesso");
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                        toastr.warning("{{ message }}", "Aviso");
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                        toastr.info("{{ message }}", "Atenção");
                    {% endif %}
                {% endfor %}
            {% endif %}

            //sobre
            $('#btnSobre').click(function() {
                $('#jnlSobre').modal('show');
            });
        });
        </script>
    </body>
</html>

core/templates/main.html
{% extends 'master.html' %}
{% load static %}
{% block conteudo %}
    <div>
        <img src="{% static 'img/background.png' %}"
             alt="Logomarca do Sistema de Gerenciamento de Papelaria"
             style="top: 0;
                    left: 0;
                    width: 75%">
    </div>
{% endblock conteudo %}